version: '3'
services:
  frontend-server:
    build: .
    environment:
      - NODE_ENV=production
      - DDF_LOCATION=https://docker.for.mac.localhost:8993
      - EXPRESS_PORT=3200
    ports:
      - "3200:3200"
