version: '3'
services:
  frontend-server:
    build: .
    environment:
      - NODE_ENV=production
      - DDF_LOCATION=https://docker.for.mac.localhost:8993
      - EXPRESS_PORT=4000
    command:
      [
        'sh',
        '-c',
        'NODE_ENV=$${NODE_ENV} DDF_LOCATION=$${DDF_LOCATION} EXPRESS_PORT=$${EXPRESS_PORT}} node bundle.middleware.js',
      ]
    ports:
      - '4000:4000'
